name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]

    - name: Build documentation
      run: |
        cd docs
        make clean && make html SPHINXOPTS="-W --keep-going"

    - name: Notice
      run: |
        echo "Documentation build successful!"
        echo "After merging this PR, you can view the latest documentation at:"
        echo "- Public docs: https://camtools.readthedocs.io/en/latest/"
        echo "- Admin panel: https://app.readthedocs.org/projects/camtools/"
